version: '3.8'

services:
  app:
    image: library-service-app
    container_name: library-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongo
      - postgres
      - clickhouse
      - nats
      - redis
      - tempo
      - grafana
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: library-service-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client port
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default

  nats:
    image: nats:latest
    container_name: library-service-nats
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
      - "6222:6222"  # Cluster connections
    command: "-js -m 8222"  # Enable JetStream and monitoring

  redis:
    image: redis:latest
    container_name: library-service-redis
    ports:
      - "6379:6379"

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "3200:3200"  # Tempo HTTP

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  rabbitmq:
    image: rabbitmq:3-management # Use the image with the management plugin
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Port for the AMQP protocol (client connections)
      - "15672:15672" # Port for the management web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/

volumes:
  tempo-data: