version: '3.8'

services:
  app:
    image: library-service-app
    container_name: library-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongo
      - postgres
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: library-service-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client port
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default

  nats:
    image: nats:latest
    container_name: library-service-nats
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
      - "6222:6222"  # Cluster connections
    command: "-js -m 8222"  # Enable JetStream and monitoring

  redis:
    image: redis:latest
    container_name: library-service-redis
    ports:
      - "6379:6379"